language: java

jdk:
  - openjdk16

sudo: false

env:
  global:
    - CODECOV_TOKEN="1cea97cd-7775-4ca2-9d51-aba7a0f68b84"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - alexeymerkulovv@gmail.com
    on_success: never # default: change
    on_failure: always # default: always